# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - engine.yaml
  - route-optimization-jsprit.yaml
  - api.yaml

# namespace to deploy all Resources to
namespace: predictivemovement-dev

configMapGenerator:
  - name: engine-properties
    envs:
      - engine.properties
  - name: common-properties
    envs:
      - common.properties
